services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server/:/app/
      - bundle:/usr/local/bundle
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./client/:/app/

volumes:
  bundle:
